### ISSUE TITLE
[ID] Some headers for tables across in all the tabs do not stick to the top of the page

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#246]
See the video here:
https://www.loom.com/share/d94f8b35e12e43d6a9f8d2a7b4c6107e

This occurs both in production and staging.

I've found this issue in

- [ ] My Grants 
- [ ] Grants 
- [ ]  Users
- [ ] Agencies
- [ ] Eligibility Codes

**Comment by glennrfisher** [comment]
This is a bootstrap-vue bug (bootstrap-vue/bootstrap-vue/issues/6961) where sortable columns add a `position-relative` class that overrides the `position: sticky` declaration.

This [comment](https://github.com/bootstrap-vue/bootstrap-vue/issues/6961#issuecomment-1174882809) has a good temporary fix to override the `position: relative` with `position: sticky`.

For example:
```css
/* packages/client/src/assets/fix-sticky-headers.css */

/*
  Fix an issue in vue-bootstrap v2.22.0:
  https://github.com/bootstrap-vue/bootstrap-vue/issues/6961 */
.b-table-sticky-header > .table.b-table > thead > tr > th {
  position: sticky !important;
}
```

```js
// packages/client/src/main.js

import './assets/fix-sticky-headers.css'
```
